"""Packages `xenium_tcr_ecology`'s reusable functions as an installable,
versioned distribution, with a lightweight API reference generated by
introspection (`17_statistical_closure_and_release/07_build_documented_software_package.py`).

**Scope:** a full Sphinx documentation build and a multi-tutorial set
are out of proportion for this milestone given this project's
already-massive governance-documented body of work -- instead, this
module builds the standard installable distribution (`python -m
build`, wheel + sdist via the project's already-configured `setuptools`
backend, `pyproject.toml`) and an auto-generated API reference (every
public function/class across every module under
`src/xenium_tcr_ecology/`, with its docstring first line -- not
hand-written prose that could drift from the code), plus one minimal,
runnable tutorial.
"""

from __future__ import annotations

import importlib
import inspect
import pkgutil
import subprocess
import sys
from pathlib import Path

from xenium_tcr_ecology.infra.exceptions import PipelineError

PACKAGE_NAME = "xenium_tcr_ecology"


def extract_docstring_summary(docstring: str | None) -> str:
    """Pure, testable: first non-empty line of a docstring, stripped of
    leading whitespace; a placeholder for a missing or empty
    docstring."""
    if not docstring:
        return "(no docstring)"
    for line in docstring.strip().splitlines():
        stripped = line.strip()
        if stripped:
            return stripped
    return "(no docstring)"


def _generate_api_reference(src_root: Path) -> str:
    lines = ["# xenium_tcr_ecology API reference (auto-generated by introspection)\n"]
    package_root = src_root / PACKAGE_NAME
    for module_info in sorted(
        pkgutil.walk_packages([str(package_root)], prefix=f"{PACKAGE_NAME}."), key=lambda m: m.name
    ):
        if module_info.ispkg:
            continue
        try:
            module = importlib.import_module(module_info.name)
        except Exception as exc:  # reported, not silently skipped
            lines.append(f"\n## `{module_info.name}`\n\n(import error, skipped: {exc})\n")
            continue
        members = [
            (name, obj)
            for name, obj in inspect.getmembers(module)
            if not name.startswith("_")
            and (inspect.isfunction(obj) or inspect.isclass(obj))
            and getattr(obj, "__module__", None) == module_info.name
        ]
        if not members:
            continue
        lines.append(f"\n## `{module_info.name}`\n")
        for name, obj in sorted(members):
            summary = extract_docstring_summary(inspect.getdoc(obj))
            lines.append(f"- `{name}`: {summary}")
    return "\n".join(lines) + "\n"


def build_software_package(project_root: Path) -> dict:
    src_root = project_root / "src"
    release_dir = project_root / "release" / "software"
    release_dir.mkdir(parents=True, exist_ok=True)

    result = subprocess.run(
        [sys.executable, "-m", "build", "--outdir", str(release_dir / "dist")],
        cwd=project_root,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise PipelineError(
            f"`python -m build` failed (exit {result.returncode}):\n{result.stdout}\n{result.stderr}"
        )

    dist_files = sorted((release_dir / "dist").glob("*"))
    if not dist_files:
        raise PipelineError("`python -m build` reported success but produced no dist files.")

    api_reference = _generate_api_reference(src_root)
    api_reference_path = release_dir / "API_REFERENCE.md"
    api_reference_path.write_text(api_reference)

    readme_path = project_root / "README.md"
    license_path = project_root / "LICENSE"
    if readme_path.is_file():
        (release_dir / "README.md").write_bytes(readme_path.read_bytes())
    if license_path.is_file():
        (release_dir / "LICENSE").write_bytes(license_path.read_bytes())

    tutorial = (
        "# Minimal tutorial: computing a degree-preserving null-model p-value\n\n"
        "```python\n"
        "import numpy as np\n"
        "from xenium_tcr_ecology.graphs.candidate_graphs import build_radius_graph\n"
        "from xenium_tcr_ecology.graphs.null_models import compute_degree_strata, free_permutation_pvalue\n\n"
        "rng = np.random.default_rng(42)\n"
        "points = rng.uniform(0, 500, size=(200, 2))\n"
        "is_tumour = np.zeros(200, dtype=bool); is_tumour[:20] = True\n"
        "is_clone = np.zeros(200, dtype=bool); is_clone[20:30] = True\n\n"
        "pvalue = free_permutation_pvalue(points, is_tumour, is_clone, rng)\n"
        "print(f'Constrained-permutation p-value: {pvalue:.4f}')\n"
        "```\n"
    )
    tutorial_path = release_dir / "TUTORIAL.md"
    tutorial_path.write_text(tutorial)

    return {
        "release_dir": str(release_dir),
        "n_dist_files": len(dist_files),
        "dist_files": [f.name for f in dist_files],
        "api_reference_path": str(api_reference_path),
    }
